version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes: 
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
       
  mysql:
    build: ./mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "3308:3306"

  app:
    build: ./node-app
    ports:
      - "4000:3000"
    volumes:
      - ./node-app/:/usr/local/app/
      - exclude:/usr/local/app/node_modules/
    depends_on:
      - redis
      - mysql
    

volumes:
  mysql_volume:
  redis_volume:
  exclude: